-- Supabase-ready schema (PostgreSQL)
-- Idempotent: re-runnable without errors; seeds require a fresh or compatible state.

-- Drop existing enums if needed (safe on rerun)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN DROP TYPE order_status; END IF;
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN DROP TYPE payment_status; END IF;
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'spice_level') THEN DROP TYPE spice_level; END IF;
END $$;

CREATE TYPE order_status AS ENUM ('cart','pending','confirmed','preparing','ready','delivering','delivered','cancelled');
CREATE TYPE payment_status AS ENUM ('pending','paid','failed','refunded');
CREATE TYPE spice_level AS ENUM ('none','mild','medium','hot','extra_hot');

-- Tables
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_token VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_session_token ON user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);

CREATE TABLE IF NOT EXISTS menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES menu_categories(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  image_url VARCHAR(255),
  is_available BOOLEAN DEFAULT TRUE,
  is_vegetarian BOOLEAN DEFAULT FALSE,
  is_vegan BOOLEAN DEFAULT FALSE,
  spice_level spice_level DEFAULT 'none',
  calories INT,
  preparation_time INT,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON menu_items(category_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_available ON menu_items(is_available);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_number VARCHAR(50) NOT NULL UNIQUE,
  total_amount NUMERIC(10,2) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  tax_amount NUMERIC(10,2) DEFAULT 0,
  delivery_fee NUMERIC(10,2) DEFAULT 0,
  discount_amount NUMERIC(10,2) DEFAULT 0,
  status order_status DEFAULT 'cart',
  payment_status payment_status DEFAULT 'pending',
  payment_method VARCHAR(50),
  delivery_address TEXT,
  delivery_phone VARCHAR(20),
  delivery_instructions TEXT,
  estimated_delivery_time TIMESTAMPTZ,
  notes TEXT,
  occasion VARCHAR(50),
  meal_plan_name VARCHAR(200),
  guest_count INT DEFAULT 1,
  event_date DATE,
  event_time TIME,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id BIGINT NOT NULL REFERENCES menu_items(id) ON DELETE RESTRICT,
  quantity INT NOT NULL DEFAULT 1,
  unit_price NUMERIC(10,2) NOT NULL,
  total_price NUMERIC(10,2) NOT NULL,
  customizations JSONB,
  special_instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_menu ON order_items(menu_item_id);

CREATE TABLE IF NOT EXISTS meal_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  occasion VARCHAR(50) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  type VARCHAR(20) DEFAULT 'veg',
  items TEXT NOT NULL,
  image_url VARCHAR(255),
  recommended BOOLEAN DEFAULT FALSE,
  popular BOOLEAN DEFAULT FALSE,
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_meal_plans_occasion ON meal_plans(occasion);
CREATE INDEX IF NOT EXISTS idx_meal_plans_active ON meal_plans(is_active);

-- Trigger to keep updated_at fresh
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_users BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_menu_categories BEFORE UPDATE ON menu_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_menu_items BEFORE UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_orders BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_order_items BEFORE UPDATE ON order_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_meal_plans BEFORE UPDATE ON meal_plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed data ------------------------------------------------------------
-- Seed a user first so FK on orders works
INSERT INTO users (id, full_name, email, password, phone, address)
VALUES (1, 'Seed User', 'seed@example.com', 'changeme', '+91 90000 00000', 'Seeder Address')
ON CONFLICT (id) DO NOTHING;
-- Ensure identity sequence is at least the max id
SELECT setval('users_id_seq', (SELECT GREATEST(MAX(id), 1) FROM users));

INSERT INTO menu_categories (name, description, image_url, display_order) VALUES
('Meal Box', 'Complete meal boxes with variety of dishes', '/meal-box.jpg', 1),
('Snack Box', 'Delicious snacks and appetizers', '/snack-box.jpg', 2),
('Bowls', 'Customizable rice and noodle bowls', '/bowls.jpg', 3),
('Buffet', 'All-you-can-eat buffet options', '/buffet.jpg', 4)
ON CONFLICT DO NOTHING;

INSERT INTO menu_items (category_id, name, description, price, is_vegetarian, is_vegan, spice_level, calories) VALUES
(1, 'Classic Meal Box', 'Rice, Dal, Vegetables, Roti, Salad', 150.00, TRUE, FALSE, 'mild', 650),
(1, 'Deluxe Meal Box', 'Rice, Dal, Paneer, Vegetables, Roti, Salad, Dessert', 200.00, TRUE, FALSE, 'medium', 850),
(1, 'Non-Veg Meal Box', 'Rice, Dal, Chicken Curry, Vegetables, Roti, Salad', 250.00, FALSE, FALSE, 'medium', 900),
(1, 'Premium Meal Box', 'Biryani, Curry, Raita, Salad, Dessert', 300.00, FALSE, FALSE, 'hot', 1000),
(2, 'Samosa Box (6 pcs)', 'Crispy vegetable samosas with chutney', 80.00, TRUE, TRUE, 'mild', 450),
(2, 'Spring Roll Box (8 pcs)', 'Mixed vegetable spring rolls', 100.00, TRUE, TRUE, 'mild', 400),
(2, 'Pakora Mix Box', 'Assorted pakoras with mint chutney', 90.00, TRUE, TRUE, 'medium', 380),
(2, 'Chicken Wings Box', 'Spicy chicken wings with dip', 180.00, FALSE, FALSE, 'hot', 550),
(3, 'Veg Fried Rice Bowl', 'Mixed vegetables with fried rice', 120.00, TRUE, TRUE, 'mild', 500),
(3, 'Chicken Fried Rice Bowl', 'Chicken with fried rice and vegetables', 160.00, FALSE, FALSE, 'medium', 650),
(3, 'Paneer Tikka Bowl', 'Paneer tikka with rice and curry', 140.00, TRUE, FALSE, 'medium', 600),
(3, 'Noodle Bowl', 'Stir-fried noodles with vegetables', 130.00, TRUE, TRUE, 'mild', 480),
(4, 'Veg Buffet', 'Unlimited vegetarian dishes', 350.00, TRUE, FALSE, 'mild', 1200),
(4, 'Non-Veg Buffet', 'Unlimited veg and non-veg dishes', 450.00, FALSE, FALSE, 'medium', 1500),
(4, 'Premium Buffet', 'Unlimited premium dishes with live counter', 600.00, FALSE, FALSE, 'medium', 1800)
ON CONFLICT DO NOTHING;

INSERT INTO meal_plans (id, name, occasion, price, type, items, image_url, recommended, popular) VALUES
(1, 'Premium Corporate Lunch', 'corporate', 299.00, 'veg',
 'Paneer Butter Masala, Dal Makhani, Jeera Rice, Garlic Naan, Raita, Gulab Jamun',
 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400', TRUE, TRUE),
(2, 'Executive Dining Box', 'corporate', 399.00, 'non-veg',
 'Butter Chicken, Dal Tadka, Pulao, Butter Naan, Salad, Dessert',
 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400', TRUE, FALSE),
(3, 'Grand Wedding Feast', 'wedding', 599.00, 'veg',
 'Veg Biryani, Paneer Tikka, Dal Tadka, Butter Naan, Raita, Rasmalai',
 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400', TRUE, TRUE),
(4, 'Royal Wedding Platter', 'wedding', 799.00, 'non-veg',
 'Chicken Biryani, Mutton Korma, Paneer Tikka, Naan, Raita, Gulab Jamun',
 'https://images.unsplash.com/photo-1583850111854-6b62afd4f5e4?w=400', TRUE, FALSE),
(5, 'Birthday Special Box', 'birthday', 199.00, 'veg',
 'Chole Bhature, Paneer Tikka, Veg Biryani, Raita, Ice Cream',
 'https://images.unsplash.com/photo-1558636508-e0db3814bd1d?w=400', FALSE, TRUE),
(6, 'Kids Birthday Combo', 'birthday', 249.00, 'veg',
 'Pizza Slices, Pasta, French Fries, Nuggets, Cake, Ice Cream',
 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400', TRUE, FALSE),
(7, 'House Party Deluxe', 'houseParty', 299.00, 'veg',
 'Pav Bhaji, Paneer Tikka, Spring Rolls, Samosas, Gulab Jamun',
 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400', TRUE, TRUE),
(8, 'Party Mix Non-Veg', 'houseParty', 399.00, 'non-veg',
 'Chicken Wings, Seekh Kebab, Spring Rolls, Biryani, Dessert',
 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400', FALSE, FALSE),
(9, 'Pooja Special Thali', 'pooja', 249.00, 'veg',
 'Puri, Chole, Paneer Sabzi, Rice, Kheer, Halwa',
 'https://images.unsplash.com/photo-1546069901-c199b53894e7?w=400', TRUE, TRUE),
(10, 'Festival Grand Thali', 'pooja', 349.00, 'veg',
 'Puri, Chole, Paneer, Dal, Rice, Sweets Platter, Halwa',
 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;
SELECT setval('meal_plans_id_seq', (SELECT GREATEST(MAX(id), 1) FROM meal_plans));

-- Orders seed relies on user_id = 1 existing
INSERT INTO orders (id, user_id, order_number, occasion, meal_plan_name, guest_count,
  event_date, event_time, total_amount, subtotal, tax_amount, delivery_fee,
  status, delivery_address, delivery_phone, created_at)
VALUES
(1, 1, 'ORD-1234', 'Corporate Event', 'Premium Corporate Lunch', 100,
 '2026-02-10', '12:00:00', 35900, 29900, 1495, 50, 'confirmed',
 '123 Corporate Blvd, Tech Park, Mumbai', '+91 98765 43210', '2026-02-05 10:30:00'),
(2, 1, 'ORD-1233', 'Wedding', 'Grand Wedding Feast', 500,
 '2026-02-15', '19:00:00', 349500, 299500, 14975, 50, 'pending',
 'Grand Palace, Wedding Hall, Andheri, Mumbai', '+91 91234 56789', '2026-02-04 15:20:00'),
(3, 1, 'ORD-1232', 'Birthday Party', 'Birthday Special Box', 50,
 '2026-02-09', '18:00:00', 9950, 9950, 497, 50, 'delivered',
 '45 Green Park, Bandra West, Mumbai', '+91 98888 12345', '2026-02-03 09:15:00'),
(4, 1, 'ORD-1231', 'Corporate Event', 'Executive Dining Box', 75,
 '2026-02-12', '13:00:00', 42000, 29925, 1496, 50, 'confirmed',
 '456 Business Park, Powai, Mumbai', '+91 98765 43210', '2026-02-02 11:45:00'),
(5, 1, 'ORD-1230', 'House Party', 'House Party Deluxe', 30,
 '2026-02-08', '20:00:00', 10470, 8970, 448, 50, 'delivered',
 '789 Residential Complex, Andheri, Mumbai', '+91 97777 88888', '2026-02-01 16:30:00')
ON CONFLICT (id) DO NOTHING;
SELECT setval('orders_id_seq', (SELECT GREATEST(MAX(id), 1) FROM orders));

-- Order items omitted; add as needed after matching order/menu_item ids.
